export const PRODUCTS_PLACEHOLDER = [
  {
    product_id: "cjx8f92k0001a0s3p9f1q1ab",
    product_title: "Smart Zigbee Multi-Sensor",
    product_image: "/product__placeholder.png",
    product_available: true,
    product_description: "A compact Zigbee-based multi-sensor capable of detecting temperature, humidity, and motion. Designed for low power operation and seamless integration with home automation hubs.",
    product_categories: ["sensors", "environment", "zigbee"],
  },
  {
    product_id: "cjx8f92k0001b0s3p9f1q1ac",
    product_title: "LoRaWAN Air Quality Monitor",
    product_image: "/product__placeholder__2.png",
    product_available: false,
    product_description: "An industrial-grade LoRaWAN air quality node that measures PM2.5, CO₂, and VOC levels. Ideal for factories, smart buildings, and environmental monitoring deployments.",
    product_categories: ["sensors", "environment", "lorawan"],
  },
  {
    product_id: "cjx8f92k0001c0s3p9f1q1ad",
    product_title: "WiFi Smart Plug Energy Meter",
    product_image: "/product__placeholder__3.png",
    product_available: true,
    product_description: "A WiFi-enabled smart plug capable of remote switching and real-time energy usage monitoring. Supports automation routines and integrates with major smart home platforms.",
    product_categories: ["actuator", "power", "wifi"],
  },
  {
    product_id: "cjx8f92k0001d0s3p9f1q1ae",
    product_title: "Industrial IoT Gateway GX-400",
    product_image: "/product__placeholder__4.png",
    product_available: true,
    product_description: "A powerful industrial IoT gateway supporting Ethernet, WiFi, and LTE connectivity. Features edge processing, secure data routing, and cloud integration capabilities.",
    product_categories: ["gateway", "industrial", "edge-computing"],
  },
  {
    product_id: "cjx8f92k0001d0s3p9f1q2828",
    product_title: "Sensor analog induktif dengan IO-Link",
    product_image: "/product__placeholder__5.png",
    product_available: true,
    product_description:
      "Pengukuran jarak non-kontak hingga 15 mm, oOutput arus yang dilinierisasi secara presisi, Rentang suhu pengoperasian yang luasKemampuan pengulangan tinggi,  Display LED untuk memeriksa jangkauan kerja dan pengoperasian.",
    product_categories: ["sensors", "industrial"],
  },
  {
    product_id: "plh0010001",
    product_title: "PC M2 i5-1145G7E 16GB 1024SSD noOS",
    product_image: "/product__placeholder__6.png",
    product_available: true,
    product_description: "Ultra-compact PLC controller designed for small automation systems. Features high-speed processing, modular expansion support, and integrated communication ports.",
    product_categories: ["plc", "automation", "industrial"],
  },
  {
    product_id: "plh0010002",
    product_title: "Modular Power Supply Unit S-2400 Pro",
    product_image: "/product__placeholder__2.png",
    product_available: true,
    product_description: "High-efficiency industrial power supply with overcurrent protection, wide voltage input support, and long operational lifespan for harsh environments.",
    product_categories: ["power-supply", "industrial"],
  },
  {
    product_id: "plh0010003",
    product_title: "Industrial WiFi Access Point APX-900",
    product_image: "/product__placeholder__3.png",
    product_available: true,
    product_description: "Rugged industrial-grade WiFi access point with MIMO antennas, dust-proof enclosure, and secure wireless communication for factory environments.",
    product_categories: ["networking", "wireless", "industrial"],
  },
  {
    product_id: "plh0010004",
    product_title: "High-Precision Pressure Sensor PX-710",
    product_image: "/product__placeholder__4.png",
    product_available: true,
    product_description: "High-precision pressure sensor with stainless steel diaphragm, ideal for hydraulic and pneumatic systems. Supports analog and digital output modes.",
    product_categories: ["sensors", "pressure", "industrial"],
  },
  {
    product_id: "plh0010005",
    product_title: "Advanced HMI Panel Touch-10 Lite",
    product_image: "/product__placeholder__5.png",
    product_available: false,
    product_description: "10-inch touchscreen HMI panel with multi-protocol support, intuitive UI configuration, and durable front panel suitable for industrial automation.",
    product_categories: ["hmi", "display", "industrial"],
  },
  {
    product_id: "plh0010001",
    product_title: "PC M2 i5-1145G7E 16GB 1024SSD noOS",
    product_image: "/product__placeholder__6.png",
    product_available: true,
    product_description: "Ultra-compact PLC controller designed for small automation systems. Features high-speed processing, modular expansion support, and integrated communication ports.",
    product_categories: ["plc", "automation", "industrial"],
  },
  {
    product_id: "plh0010002",
    product_title: "Modular Power Supply Unit S-2400 Pro",
    product_image: "/product__placeholder__2.png",
    product_available: true,
    product_description: "High-efficiency industrial power supply with overcurrent protection, wide voltage input support, and long operational lifespan for harsh environments.",
    product_categories: ["power-supply", "industrial"],
  },
  {
    product_id: "plh0010003",
    product_title: "Industrial WiFi Access Point APX-900",
    product_image: "/product__placeholder__3.png",
    product_available: true,
    product_description: "Rugged industrial-grade WiFi access point with MIMO antennas, dust-proof enclosure, and secure wireless communication for factory environments.",
    product_categories: ["networking", "wireless", "industrial"],
  },
  {
    product_id: "plh0010004",
    product_title: "High-Precision Pressure Sensor PX-710",
    product_image: "/product__placeholder__4.png",
    product_available: true,
    product_description: "High-precision pressure sensor with stainless steel diaphragm, ideal for hydraulic and pneumatic systems. Supports analog and digital output modes.",
    product_categories: ["sensors", "pressure", "industrial"],
  },
  {
    product_id: "plh0010005",
    product_title: "Advanced HMI Panel Touch-10 Lite",
    product_image: "/product__placeholder__5.png",
    product_available: false,
    product_description: "10-inch touchscreen HMI panel with multi-protocol support, intuitive UI configuration, and durable front panel suitable for industrial automation.",
    product_categories: ["hmi", "display", "industrial"],
  },
];
