export const metadata: Metadata = {
  title: "Aurora | Products",
  description: "Generated by create next app",
};

import { Metadata } from "next";
import ProductGridContainer from "@/components/layouts/products/product-grid-container";
import DynamicAccordion from "@/components/common/dynamic-accordion";
import { Suspense } from "react";
import { ProductCardLoading } from "@/components/layouts/products/product-card";

export default function ShopPage() {
  return <ShopFilters />;
}

function ShopFilters() {
  return (
    <div className="sm:mt-16">
      <ShopMainLayout />
    </div>
  );
}

function ShopMainLayout() {
  return (
    <main className="p-4 py-10 grid md:grid-cols-[1fr_2.5fr] gap-4 relative max-w-7xl mx-auto">
      <div className="h-full">
        <aside className="flex-shrink-0 border rounded-lg border-border p-4 sticky top-24">
          <p className="pb-4 border-b border-border text-muted-foreground text-sm">filter by</p>
          <Suspense fallback={<p>Loading filters...</p>}>
            <DynamicAccordion />
          </Suspense>
        </aside>
      </div>
      <Suspense fallback={<ProductCardLoading className="sm:grid-cols-2 lg:grid-cols-3" count={6} />}>
        <ProductGridContainer />
      </Suspense>
    </main>
  );
}
