export const metadata: Metadata = {
  title: "Aurora | Prodducts",
  description: "Generated by create next app",
};

import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from "@/components/ui/input-group";
import { SearchIcon } from "lucide-react";

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

import {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from "@/components/ui/pagination";

import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";

import { Checkbox } from "@/components/ui/checkbox";
import { Metadata } from "next";
import ProductCard from "@/components/layouts/products/product-card";

export default function ShopPage() {
  return (
    <>
      <ShopFilters />
    </>
  );
}

function ShopFilters() {
  return (
    <div className="mt-16">
      <header className="bg-accent text-foreground p-4">
        <ul className="flex items-center justify-evenly gap-4 max-w-4xl mx-auto ">
          <p>Special offers</p>
          <p>Best Sellers</p>
          <p>Arrival</p>
          <p>Recommended</p>

          <InputGroup className="max-w-sm">
            <InputGroupInput placeholder="Search..." />
            <InputGroupAddon>
              <SearchIcon />
            </InputGroupAddon>
            <InputGroupAddon align="inline-end">12 results</InputGroupAddon>
          </InputGroup>
        </ul>
      </header>
      <ShopMainLayout />
    </div>
  );
}

function ShopMainLayout() {
  return (
    <main className="p-4 py-10 grid md:grid-cols-[1fr_2.5fr] gap-4 relative max-w-7xl mx-auto">
      <div className="h-full">
        <aside className="flex-shrink-0 border rounded-lg border-border p-4 sticky top-24">
          <p className="pb-4 border-b border-border text-muted-foreground text-sm">
            filter by
          </p>
          <AccordionDemo />
        </aside>
      </div>
      <section className="w-full px-4">
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
          <ProductCard />
        </div>
        <PaginationDemo />
      </section>
    </main>
  );
}

function PaginationDemo({ className }: { className?: string }) {
  return (
    <Pagination className="mt-10">
      <PaginationContent>
        <PaginationItem>
          <PaginationPrevious href="#" />
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#">1</PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#" isActive>
            2
          </PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationLink href="#">3</PaginationLink>
        </PaginationItem>
        <PaginationItem>
          <PaginationEllipsis />
        </PaginationItem>
        <PaginationItem>
          <PaginationNext href="#" />
        </PaginationItem>
      </PaginationContent>
    </Pagination>
  );
}

function AccordionDemo() {
  return (
    <Accordion
      type="single"
      collapsible
      className="w-full"
      defaultValue="item-1"
    >
      <AccordionItem value="item-1">
        <AccordionTrigger className="cursor-pointer">Product</AccordionTrigger>
        <AccordionContent className="flex flex-col gap-4 text-balance">
          <RadioGroupDemo />
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-2">
        <AccordionTrigger className="cursor-pointer">
          System support
        </AccordionTrigger>
        <AccordionContent className="flex flex-col gap-4 text-balance">
          <CheckboxDemo />
        </AccordionContent>
      </AccordionItem>
      <AccordionItem value="item-3">
        <AccordionTrigger className="cursor-pointer">
          Interface
        </AccordionTrigger>
        <AccordionContent className="flex flex-col gap-4 text-balance">
          <p>
            We stand behind our products with a comprehensive 30-day return
            policy. If you&apos;re not completely satisfied, simply return the
            item in its original condition.
          </p>
          <p>
            Our hassle-free return process includes free return shipping and
            full refunds processed within 48 hours of receiving the returned
            item.
          </p>
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  );
}

export function RadioGroupDemo() {
  return (
    <RadioGroup defaultValue="comfortable">
      <div className="flex items-center gap-3">
        <RadioGroupItem value="default" id="r1" className="cursor-pointer" />
        <Label htmlFor="r1" className="cursor-pointer">
          IoT Gateway
        </Label>
      </div>
      <div className="flex items-center gap-3">
        <RadioGroupItem
          value="comfortable"
          id="r2"
          className="cursor-pointer"
        />
        <Label htmlFor="r2" className="cursor-pointer">
          Router
        </Label>
      </div>
      <div className="flex items-center gap-3">
        <RadioGroupItem value="compact" id="r3" className="cursor-pointer" />
        <Label htmlFor="r3" className="cursor-pointer">
          Repeater
        </Label>
      </div>
    </RadioGroup>
  );
}

export function CheckboxDemo() {
  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center gap-3">
        <Checkbox id="terms" />
        <Label htmlFor="terms">Ubuntu</Label>
      </div>
      <div className="flex items-start gap-3">
        <Checkbox id="terms-2" defaultChecked />
        <div className="grid gap-2">
          <Label htmlFor="terms-2">Windows</Label>
          <p className="text-muted-foreground text-sm">
            By clicking this checkbox, you agree to the terms and conditions.
          </p>
        </div>
      </div>
      {/* <div className="flex items-start gap-3">
        <Checkbox id="toggle" disabled />
        <Label htmlFor="toggle">Enable notifications</Label>
      </div>
      <Label className="hover:bg-accent/50 flex items-start gap-3 rounded-lg border p-3 has-[[aria-checked=true]]:border-blue-600 has-[[aria-checked=true]]:bg-blue-50 dark:has-[[aria-checked=true]]:border-blue-900 dark:has-[[aria-checked=true]]:bg-blue-950">
        <Checkbox
          id="toggle-2"
          defaultChecked
          className="data-[state=checked]:border-blue-600 data-[state=checked]:bg-blue-600 data-[state=checked]:text-white dark:data-[state=checked]:border-blue-700 dark:data-[state=checked]:bg-blue-700"
        />
        <div className="grid gap-1.5 font-normal">
          <p className="text-sm leading-none font-medium">
            Enable notifications
          </p>
          <p className="text-muted-foreground text-sm">
            You can enable or disable notifications at any time.
          </p>
        </div>
      </Label> */}
    </div>
  );
}
