export const PRODUCTS_PLACEHOLDER = [
  {
    product_id: "cjx8f92k0001a0s3p9f1q1ab",
    product_title: "Smart Zigbee Multi-Sensor",
    product_image: "/product__placeholder.png",
    product_available: true,
    product_description: "A compact Zigbee-based multi-sensor capable of detecting temperature, humidity, and motion. Designed for low power operation and seamless integration with home automation hubs.",
    product_categories: ["sensors", "environment", "zigbee"],
  },
  {
    product_id: "cjx8f92k0001b0s3p9f1q1ac",
    product_title: "LoRaWAN Air Quality Monitor",
    product_image: "/product__placeholder.png",
    product_available: false,
    product_description: "An industrial-grade LoRaWAN air quality node that measures PM2.5, CO₂, and VOC levels. Ideal for factories, smart buildings, and environmental monitoring deployments.",
    product_categories: ["sensors", "environment", "lorawan"],
  },
  {
    product_id: "cjx8f92k0001c0s3p9f1q1ad",
    product_title: "WiFi Smart Plug Energy Meter",
    product_image: "/product__placeholder.png",
    product_available: true,
    product_description: "A WiFi-enabled smart plug capable of remote switching and real-time energy usage monitoring. Supports automation routines and integrates with major smart home platforms.",
    product_categories: ["actuator", "power", "wifi"],
  },
  {
    product_id: "cjx8f92k0001d0s3p9f1q1ae",
    product_title: "Industrial IoT Gateway GX-400",
    product_image: "/product__placeholder.png",
    product_available: true,
    product_description: "A powerful industrial IoT gateway supporting Ethernet, WiFi, and LTE connectivity. Features edge processing, secure data routing, and cloud integration capabilities.",
    product_categories: ["gateway", "industrial", "edge-computing"],
  },
  {
    product_id: "cjx8f92k0001e0s3p9f1q1af",
    product_title: "BLE Temperature Beacon",
    product_image: "/product__placeholder.png",
    product_available: true,
    product_description: "A battery-powered BLE beacon that broadcasts temperature and humidity data. Optimized for indoor tracking, storage warehouses, and portable monitoring solutions.",
    product_categories: ["beacons", "ble", "sensors"],
  },
  {
    product_id: "cjx8f92k0001f0s3p9f1q1ag",
    product_title: "Smart Door & Window Contact Sensor",
    product_image: "/product__placeholder.png",
    product_available: false,
    product_description: "A low-profile contact sensor detecting door and window openings using Zigbee communication. Ideal for home security setups and automation triggers.",
    product_categories: ["security", "zigbee", "sensors"],
  },
  {
    product_id: "cjx8f92k0001g0s3p9f1q1ah",
    product_title: "GPS Asset Tracker Mini",
    product_image: "/product__placeholder.png",
    product_available: true,
    product_description: "A compact GPS tracker with long battery life designed for vehicles, equipment tracking, and logistics. Supports LTE-M/NB-IoT connectivity with geofencing features.",
    product_categories: ["tracker", "gps", "nb-iot"],
  },
];
